[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
]
name = "sam-maps"
version = "1.0.0"
authors = [{ name = "Matthijs van Andel", email = "m.p.vanandel@student.tudelft.nl" }, { name = "Hidde Boekema", email = "h.j.boekema@tudelft.nl" }]
description = "The SAM-Maps pipeline."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy==1.26.4",
    "tqdm>=4.66.1",
    "pandas>=2.2.2",
    "matplotlib>=3.8.4",
    "scipy>=1.10.1",
    "opencv-python>=4.10.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "shapely>=2.0.4",
    "pyproj>=3.6.1",
    "networkx>=3.3",
    "rasterio>=1.3.10",
    "Pillow>=10.3.0",
    "hydra-core>=1.3.2", 
    "addict>=2.4.0",
    "igraph>=0.11.8",
    "rtree>=1.2.0",
    "torchmetrics>=1.6.0",
    "lightning>=2.4.0",
    "wandb>=0.18.7",
    "tcod>=16.2.3",
    "osmnx>=2.0.0",
    "scikit-learn>=1.5.0",
    "pyquaternion>=0.9.9",
    "centerline>=1.1.1",
]

[project.optional-dependencies]
dev = ["black", "isort", "pytest", "pytest-xdist", "twine", "build"]

[project.urls]
"Homepage" = "https://gitlab.tudelft.nl/hidde_students/sam-maps#"
"Code" = "https://gitlab.tudelft.nl/hidde_students/sam-maps#"
"Bug Tracker" = "https://gitlab.tudelft.nl/hidde_students/sam-maps/-/issues" 
