
seed: 42
experiment_name: "sam_maps_4,5_4,0_3,0"
gt_datapath: "./output/ground_truth"
pred_datapath: "./output/predictions"
cache_datapath: "./output/cache"

annot_file: "/scratch/hjhboekema/mpvanandel/data/processed/lanes.gpkg"

trim_dist: 4.0
max_part_trim: 0.4

from_crs: "EPSG:4326"
target_crs: "EPSG:32631"
#bbox: [[4.35556, 52.00667, 4.36, 52.01]] #,[4.37, 52.02, 4.38, 52.03]]
bbox: [[4.35196, 52.00463, 4.37225, 52.01700]] #,[4.37, 52.02, 4.38, 52.03]]

gpus: [6]
processes_per_gpu: 3
flags: 
  save_cache: true 
  use_cache: true
  save_images: false
  verbose: false
  overwrite_tif_files: true

# parameters for ablation
w_init: 4.5

rs_module:
  mask_operator:
    constraints:
      min_width: 4.0

  warp_operator:
    safety_margin_width: 3.0



defaults:
 - _self_
 - rge_module: samroad 
 - rs_module: auto-rs
 - rc_module: auto-rc
