import pickle
import geopandas as gpd
from shapely.geometry import Point, LineString
import os
from typing import Optional


def filter_samroad_graph(samroad_graph: dict, lanes: gpd.GeoDataFrame, output_dir: str, threshold: int = 40) -> dict:
    """
    samroad_graph has the structure:
    {
    "crs": crs,
    "geolocalized_graph:
    {
        n1 : [n2, n3, ...],
        n2 : [n1, n4, ...],
        ...
    }}
    where n1, n2, ... are nodes in the graph and [n2, n3, ...] are the nodes that are connected to n1.
    lanes is a geopandas dataframe consisting of linestrings whicn form the road boundaries of the lanes.
    This function filters the samroad_graph such that only nodes that are within some threshold distance of the lanes are kept.
    It will first go through all the nodes and see if they are within some threshold to any of the linestrings and then update the graph, nodes which have no connections are also removed.
    """
    new_graph = {"crs": samroad_graph["crs"], "geolocalized_graph": {}}
    for node in samroad_graph["geolocalized_graph"].keys():
        keep_node = False
        for lane in lanes.geometry:
            if lane.distance(Point(node)) < threshold:
                keep_node = True
                break
        if keep_node:
            new_graph["geolocalized_graph"][node] = []
            for connected_node in samroad_graph["geolocalized_graph"][node]:
                if connected_node in new_graph["geolocalized_graph"]:
                    new_graph["geolocalized_graph"][node].append(connected_node)
    with open(os.path.join(output_dir, "filtered_samroad_graph.pkl"), "wb") as f:
        pickle.dump(new_graph, f)
    return new_graph


def convert_graph_to_geojson(input: str | dict, output: str):
    """
    Convert pickle graph to GeoJSON files
    The pickle graph is generated by SAMRoad and can be converted to GeoJSON files for visualization/editing in QGIS.
    """
    if isinstance(input, str):
        with open(input, "rb") as f:
            graph_data = pickle.load(f)
    else:
        graph_data = input
    graph = graph_data["geolocalized_graph"]

    crs = graph_data["crs"]

    # Convert nodes to GeoDataFrame
    nodes = []
    geom_to_id_mapping = {}
    for i, node in enumerate(graph.keys()):
        geom_to_id_mapping[node] = i
        nodes.append({"id": i, "geometry": Point(node)})

    nodes_gdf = gpd.GeoDataFrame(nodes, crs=crs)

    # Convert edges to GeoDataFrame
    edges = []
    edges_set = set()
    edge_counter = 0
    for node, connected_nodes in graph.items():
        for connected_node in connected_nodes:
            # Avoid adding the same edge twice
            if (node, connected_node) in edges_set or (
                connected_node,
                node,
            ) in edges_set:
                continue
            edges_set.add((node, connected_node))

            edges.append(
                {
                    "id": edge_counter,
                    "node1": geom_to_id_mapping[node],
                    "node2": geom_to_id_mapping[connected_node],
                    "geometry": LineString([node, connected_node]),
                }
            )
            edge_counter += 1

    edges_gdf = gpd.GeoDataFrame(edges, crs=crs)  # Use the same CRS as nodes_gdf

    # Or save as GeoJSON
    nodes_gdf.to_file(os.path.join(output, "nodes.geojson"), driver="GeoJSON")
    edges_gdf.to_file(os.path.join(output, "edges.geojson"), driver="GeoJSON")



def convert_geojson_to_graph(nodes: str, edges: str, output: Optional[str] = None):
    """
    Convert GeoJSON files to a pickle graph.
    The GeoJSON files can be edited in QGIS and the resulting graph can be used in the HD Map generation pipeline.
    """
    # Load nodes and edges data
    nodes = gpd.read_file(nodes)
    edges = gpd.read_file(edges)
    # print(edges)
    # Create a dictionary of connections by node
    connections_by_node = edges.groupby("node1")["node2"].apply(list)
    connections_by_node_reverse = edges.groupby("node2")["node1"].apply(list)
    # merge the connections_by_node and connections_by_node2 by making the node2 key in connections_by_node the same as the node1 key in connections_by_node2
    for key in connections_by_node.keys():
        if key in connections_by_node_reverse.keys():
            connections_by_node[key] = connections_by_node[key] + connections_by_node_reverse[key]
    for key in connections_by_node_reverse.keys():
        if key not in connections_by_node.keys():
            connections_by_node[key] = connections_by_node_reverse[key]

    # Map node IDs to their geometries
    node_geometry = nodes.set_index("id")["geometry"]

    # Create a dictionary of connection geometries by node geometry
    connection_geoms_dict = {
        "geolocalized_graph": {
        node_geometry.loc[node].coords[0]: [
            node_geometry.loc[conn].coords[0] for conn in conns
        ]
        for node, conns in connections_by_node.items()
        },
        "crs": nodes.crs
    }
    
    # Store the results in a pickle file
    if output is not None:
        out = os.path.join(output, "graph.pkl")
        with open(out, "wb") as f:
            pickle.dump(connection_geoms_dict, f)
    return connection_geoms_dict
